[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  YARN_PRODUCTION = "false"
  YARN_FLAGS = "--production=false --frozen-lockfile"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    configFile = "cypress.config.ts"
    record = false
