[build.environment]
  NPM_CONFIG_PRODUCTION = "false"
  YARN_PRODUCTION = "false"
  YARN_FLAGS = "--production=false --frozen-lockfile"
  NODE_VERSION = "20.16.0"
  DEBUG = "netlify-plugin-cypress"
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    configFile = "cypress.config.ts"
    record = false
